using System.IO.Compression;
using Vni.Ielts.Application.Importing;
using Vni.Ielts.Domain.Exams;
using Vni.Ielts.Infrastructure.Content.Import;
using static Vni.Ielts.Infrastructure.Tests.Content.Import.HostileArchives;

namespace Vni.Ielts.Infrastructure.Tests.Content.Import;

/// <summary>
/// docs/security/zip-ingestion-security.md § Testing, made real. Every
/// fixture is generated by <see cref="HostileArchives"/>; the limits are
/// passed explicitly and kept tight so each archive stays a few kilobytes.
///
/// The three checks that matter most — ratio, path escape, streaming quota —
/// were each watched going red with the check removed before this file was
/// accepted. → the S6 report
/// </summary>
public sealed class ExamPackageArchiveInspectorTests : IDisposable
{
    private readonly string sandbox = Path.Combine(Path.GetTempPath(), $"vni-zip-{Guid.NewGuid():n}");
    private readonly ExamPackageArchiveInspector inspector = new();

    /// <summary>Tight on purpose: a 10 KB bomb and a 4 KB file are both over-sized against these.</summary>
    private static readonly ImportArchiveLimits Tight = new(
        MaxEntries: 8,
        MaxTotalUncompressedBytes: 4_096,
        MaxEntryUncompressedBytes: 2_048,
        MaxCompressionRatio: 20,
        MaxArchiveBytes: 64 * 1024,
        ExtractionTimeout: TimeSpan.FromSeconds(10));

    private static string Error => "error";
    private static string Warning => "warning";

    // ── Signature and archive-level caps ─────────────────────────────────

    [Fact]
    public async Task A_file_that_is_not_a_zip_is_refused_by_its_first_bytes()
    {
        var result = await inspector.InspectAsync(NotAZip(), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.NotAnArchive);
    }

    [Fact]
    public async Task An_empty_archive_is_refused_as_empty_not_as_corrupt()
    {
        var result = await inspector.InspectAsync(Empty(), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.LayoutEmpty);
    }

    [Fact]
    public async Task An_upload_over_the_archive_byte_cap_is_refused_before_the_directory_is_read()
    {
        var limits = Tight with { MaxArchiveBytes = 64 };

        var result = await inspector.InspectAsync(FullPackage(), limits, default);

        AssertRefused(result, ArchiveFindingCodes.TooLarge);
    }

    [Fact]
    public async Task An_unseekable_upload_over_the_cap_is_refused_while_being_spooled()
    {
        var limits = Tight with { MaxArchiveBytes = 64 };

        var result = await inspector.InspectAsync(Unseekable(FullPackage()), limits, default);

        AssertRefused(result, ArchiveFindingCodes.TooLarge);
    }

    [Fact]
    public async Task An_unseekable_valid_upload_is_spooled_and_inspected()
    {
        var result = await inspector.InspectAsync(Unseekable(FullPackage()), Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
        Assert.Equal(4, result.Layout.PresentSkills.Count);
    }

    [Fact]
    public async Task Too_many_entries_is_refused_at_the_cap_plus_one()
    {
        var atCap = Enumerable.Range(0, Tight.MaxEntries).Select(i => File($"reading/{i}.txt")).ToArray();
        var overCap = atCap.Append(File("reading/one-more.txt")).ToArray();

        var accepted = await inspector.InspectAsync(Build(atCap), Tight, default);
        var refused = await inspector.InspectAsync(Build(overCap), Tight, default);

        Assert.True(accepted.IsAcceptable, Describe(accepted));
        AssertRefused(refused, ArchiveFindingCodes.TooManyEntries);
    }

    [Fact]
    public async Task Declared_total_over_the_cap_is_refused_from_the_central_directory_alone()
    {
        // Three entries each under the per-entry cap, together over the total.
        var text = new string('a', 1_500);
        var archive = Build(
            File("reading/a.txt", text), File("reading/b.txt", text), File("reading/c.txt", text));

        var result = await inspector.InspectAsync(archive, Tight, default);

        AssertRefused(result, ArchiveFindingCodes.TotalSizeExceeded);
    }

    [Fact]
    public async Task A_single_entry_over_the_per_entry_cap_is_refused()
    {
        var archive = Build(File("reading/big.txt", new string('a', 3_000)));

        var result = await inspector.InspectAsync(archive, Tight, default);

        AssertRefused(result, ArchiveFindingCodes.EntryTooLarge);
    }

    // ── Bomb ─────────────────────────────────────────────────────────────

    [Fact]
    public async Task A_compression_bomb_is_refused_by_its_ratio()
    {
        // 1,500 zero bytes deflate to a few dozen: well past 20:1, and under
        // the per-entry cap so that the ratio is the only check that fires.
        var bomb = Build(Bytes("reading/bomb.txt", new byte[1_500], level: CompressionLevel.SmallestSize));

        var result = await inspector.InspectAsync(bomb, Tight, default);

        AssertRefused(result, ArchiveFindingCodes.CompressionRatio);
    }

    [Fact]
    public async Task Ordinary_text_is_not_mistaken_for_a_bomb()
    {
        var prose = string.Join(' ', Enumerable.Range(0, 150).Select(i => $"word{i % 37}"));

        var result = await inspector.InspectAsync(Build(File("reading/prose.txt", prose)), Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
    }

    // ── Paths ────────────────────────────────────────────────────────────

    [Fact]
    public async Task Dot_dot_traversal_is_refused_as_path_escape()
    {
        var result = await inspector.InspectAsync(Traversal(), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathEscape, "../../evil.txt");
    }

    [Fact]
    public async Task Backslash_traversal_is_normalised_then_refused()
    {
        var result = await inspector.InspectAsync(BackslashTraversal(), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathEscape);
    }

    [Theory]
    [InlineData("/etc/passwd")]
    [InlineData(@"C:\x.txt")]
    [InlineData("//server/share/x.txt")]
    public async Task Absolute_paths_are_refused(string name)
    {
        var result = await inspector.InspectAsync(Build(File(name)), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathEscape);
    }

    [Fact]
    public async Task A_null_byte_in_a_name_is_refused()
    {
        var result = await inspector.InspectAsync(NullByte(), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathInvalid);
        Assert.DoesNotContain('\0', result.Findings[0].Path);
    }

    [Theory]
    [InlineData("reading/CON.json")]
    [InlineData("reading/con")]
    [InlineData("reading/LPT1.txt")]
    [InlineData("reading/NUL/x.txt")]
    public async Task Reserved_device_names_are_refused_case_insensitively(string name)
    {
        var result = await inspector.InspectAsync(Build(File(name)), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathInvalid);
    }

    [Theory]
    [InlineData("reading/trailing-dot.")]
    [InlineData("reading/trailing-space ")]
    [InlineData("reading/./x.txt")]
    [InlineData("reading//x.txt")]
    [InlineData("reading/what?.txt")]
    [InlineData("reading/a|b.txt")]
    public async Task Names_the_filesystem_would_rewrite_or_refuse_are_refused_here_first(string name)
    {
        var result = await inspector.InspectAsync(Build(File(name)), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathInvalid);
    }

    [Fact]
    public async Task A_right_to_left_override_in_a_name_is_refused()
    {
        var result = await inspector.InspectAsync(RightToLeftOverride(), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathInvalid);
        Assert.DoesNotContain('\u202E', result.Findings[0].Path);
    }

    [Fact]
    public async Task Vietnamese_names_in_either_unicode_form_are_accepted_and_deduplicated()
    {
        // "Bài đọc" composed (NFC) and decomposed (NFD): the same name twice.
        var composed = "reading/Bài đọc.txt".Normalize(System.Text.NormalizationForm.FormC);
        var decomposed = composed.Normalize(System.Text.NormalizationForm.FormD);

        var single = await inspector.InspectAsync(Build(File(decomposed)), Tight, default);
        var both = await inspector.InspectAsync(Build(File(composed), File(decomposed)), Tight, default);

        Assert.True(single.IsAcceptable, Describe(single));
        Assert.Equal(composed, single.Layout.EntriesBySkill[ExamModule.Reading].All.Single());
        AssertRefused(both, ArchiveFindingCodes.PathInvalid);
    }

    [Fact]
    public async Task Names_differing_only_by_case_are_duplicates()
    {
        var result = await inspector.InspectAsync(
            Build(File("reading/Passage.txt"), File("reading/passage.txt")), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathInvalid);
    }

    // ── Entry kinds ──────────────────────────────────────────────────────

    [Fact]
    public async Task A_symlink_entry_is_refused()
    {
        var result = await inspector.InspectAsync(Symlink(), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.EntryNotRegular);
    }

    [Fact]
    public async Task A_unix_regular_file_attribute_is_accepted()
    {
        var archive = Build(Bytes("reading/x.txt", "x"u8.ToArray(), UnixRegular));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
    }

    [Theory]
    [InlineData("reading/inner.zip")]
    [InlineData("reading/inner.RAR")]
    [InlineData("listening/audio.7z")]
    public async Task A_nested_archive_is_refused_without_being_opened(string name)
    {
        var result = await inspector.InspectAsync(Build(File(name, "PK")), Tight, default);

        AssertRefused(result, ArchiveFindingCodes.NestedArchive);
    }

    [Fact]
    public async Task Directory_entries_are_allowed_and_do_not_count_as_files()
    {
        // Empty text, on purpose: a real ZIP writer's directory entry carries
        // no bytes, and `Build` only omits an entry's content stream when a
        // trailing-slash name pairs with empty content — the default text
        // would make these look like a folder secretly carrying a payload,
        // which the inspector correctly refuses (`ENTRY_NOT_REGULAR`).
        var archive = Build(File("reading/", ""), File("reading/de/", ""), File("reading/de/x.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
        Assert.Equal(["reading/de/x.txt"], result.Layout.EntriesBySkill[ExamModule.Reading].All);
    }

    // ── Roles (IP-02) ────────────────────────────────────────────────────

    [Fact]
    public async Task A_role_folder_separates_the_paper_from_its_answer_key()
    {
        var archive = Build(
            File("reading/de/passage.txt"),
            File("reading/dap-an/key.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
        var reading = result.Layout.EntriesBySkill[ExamModule.Reading];
        Assert.Equal("reading/de/passage.txt", Assert.Single(reading.Paper));
        Assert.Equal("reading/dap-an/key.txt", Assert.Single(reading.Key));
    }

    [Theory]
    [InlineData("paper", "key")]
    [InlineData("QUESTIONS", "ANSWERS")]
    [InlineData("de", "dapan")]
    public async Task Role_folder_names_are_accepted_in_every_spelling_and_case(string paper, string key)
    {
        var archive = Build(File($"listening/{paper}/q.txt"), File($"listening/{key}/k.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        var listening = result.Layout.EntriesBySkill[ExamModule.Listening];
        Assert.Single(listening.Paper);
        Assert.Single(listening.Key);
    }

    /// <summary>
    /// Packages imported before role folders existed put their files straight
    /// under the skill folder. Those are papers, and they must keep working —
    /// otherwise this change silently empties every historical package.
    /// </summary>
    [Fact]
    public async Task A_file_with_no_role_folder_is_still_a_paper()
    {
        var result = await inspector.InspectAsync(Build(File("reading/passage.txt")), Tight, default);

        var reading = result.Layout.EntriesBySkill[ExamModule.Reading];
        Assert.Equal("reading/passage.txt", Assert.Single(reading.Paper));
        Assert.Empty(reading.Key);
    }

    /// <summary>
    /// <b>A misspelled key folder must not degrade in silence.</b>
    /// <c>reading/dap_an/</c> — an underscore where the hyphen belongs, or a
    /// diacritic mangled by a ZIP tool writing CP437 — matches no role name,
    /// so the file is classified as paper and concatenated into the text sent
    /// to the model. That is the 2026-09-02 configuration reached by a typo,
    /// and nothing said so: the unknown-entry warning was raised only for an
    /// unrecognised <i>top-level</i> folder. An operator who believed they had
    /// supplied a key then saw the fabrication warnings that followed and
    /// cleared them as false alarms.
    ///
    /// The classification is deliberately unchanged — <c>reading/figures/</c>
    /// is a legitimate subdirectory and has always been paper. What this pins
    /// is that the fall-through is named.
    /// </summary>
    [Fact]
    public async Task A_second_level_folder_that_matches_no_role_fails_closed_and_is_excluded_from_paper()
    {
        var archive = Build(File("reading/de/passage.txt"), File("reading/dap_an/key.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.False(result.IsAcceptable, "Inspection must fail closed for unknown role folder.");
        var finding = Assert.Single(
            result.Findings,
            f => f.Code == ArchiveFindingCodes.LayoutUnknownRoleFolder);
        Assert.Equal(Error, finding.Severity);
        Assert.Equal("reading/dap_an/", finding.Path);

        // Security guarantee: unknown role folder content NEVER enters Paper (and thus never enters AI)
        var reading = result.Layout.EntriesBySkill[ExamModule.Reading];
        Assert.DoesNotContain("reading/dap_an/key.txt", reading.Paper);
        Assert.Empty(reading.Key);
    }

    /// <summary>
    /// The other half: a folder that <i>is</i> a role name raises nothing. A
    /// warning on a correctly named package is how a check gets switched off.
    /// </summary>
    [Fact]
    public async Task A_recognised_role_folder_raises_no_unknown_entry_warning()
    {
        var archive = Build(File("reading/de/passage.txt"), File("reading/dap-an/key.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.DoesNotContain(
            result.Findings, f => f.Code == ArchiveFindingCodes.LayoutUnknownRoleFolder);
        Assert.DoesNotContain(result.Findings, f => f.Code == ArchiveFindingCodes.LayoutUnknownEntry);
    }

    /// <summary>
    /// The two codes are not interchangeable, and this is the reason: an
    /// unknown <i>top-level</i> folder means the files were <b>ignored</b>, and
    /// <c>__MACOSX/</c> is that case on every package a macOS ZIP tool wrote.
    /// It keeps <c>LAYOUT_UNKNOWN_ENTRY</c> and is not routed to the draft, so
    /// it cannot block a correct package. Only the role-folder code is.
    /// </summary>
    [Fact]
    public async Task An_ignored_top_level_folder_keeps_the_unknown_entry_code()
    {
        var archive = Build(File("reading/p1.txt"), File("__MACOSX/._p1.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        var finding = Assert.Single(result.Findings);
        Assert.Equal(ArchiveFindingCodes.LayoutUnknownEntry, finding.Code);
        Assert.NotEqual(ArchiveFindingCodes.LayoutUnknownRoleFolder, finding.Code);
    }

    /// <summary>
    /// The role is read from the canonicalised path, after every traversal check
    /// has already run. A package that tries to reach a role folder by climbing
    /// must still be refused as traversal, not quietly filed as a key.
    /// </summary>
    [Fact]
    public async Task A_traversal_attempt_through_a_role_folder_is_still_refused()
    {
        var archive = Build(File("reading/de/../../../dap-an/evil.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        AssertRefused(result, ArchiveFindingCodes.PathEscape);
    }

    // ── Layout (P-18) ────────────────────────────────────────────────────

    [Fact]
    public async Task A_full_four_folder_package_is_acceptable_with_all_skills_present()
    {
        var result = await inspector.InspectAsync(FullPackage(), Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
        Assert.Empty(result.Findings);
        Assert.Equal(
            [ExamModule.Reading, ExamModule.Listening, ExamModule.Writing, ExamModule.Speaking],
            result.Layout.PresentSkills);
        Assert.Equal(["writing/task-1.txt"], result.Layout.EntriesBySkill[ExamModule.Writing].All);
    }

    [Fact]
    public async Task A_partial_package_creates_only_the_skills_whose_folders_exist()
    {
        var archive = Build(File("Reading/p1.docx", "r"), File("LISTENING/s1.mp3", "l"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
        Assert.Equal([ExamModule.Reading, ExamModule.Listening], result.Layout.PresentSkills);
        Assert.False(result.Layout.EntriesBySkill.ContainsKey(ExamModule.Writing));
    }

    [Fact]
    public async Task A_stray_root_file_is_a_warning_and_the_package_stays_acceptable()
    {
        var archive = Build(File("reading/p1.txt"), File("notes.txt"), File("__MACOSX/._p1.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
        Assert.All(result.Findings, f => Assert.Equal(Warning, f.Severity));
        Assert.Equal(
            [ArchiveFindingCodes.LayoutUnknownEntry, ArchiveFindingCodes.LayoutUnknownEntry],
            result.Findings.Select(f => f.Code));
        Assert.Equal(["__MACOSX/", "notes.txt"], result.Layout.UnknownEntries);
    }

    [Fact]
    public async Task A_package_with_no_skill_folder_is_refused_as_empty()
    {
        var archive = Build(File("Cam18/reading/p1.txt"), File("readme.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.False(result.IsAcceptable);
        Assert.Contains(result.Findings, f => f.Code == ArchiveFindingCodes.LayoutEmpty && f.Severity == Error);
        Assert.Empty(result.Layout.PresentSkills);
    }

    [Fact]
    public async Task A_root_manifest_and_exam_json_pair_is_accepted_as_the_structured_route()
    {
        // The same manifest.json + exam.json shape /admin/packages
        // (PackageStructuralValidator) already accepts — one ZIP format
        // regardless of which screen imports it.
        var archive = Build(File("manifest.json", "{}"), File("exam.json", "{}"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
        Assert.Empty(result.Findings);
        Assert.Equal(["exam.json"], result.Layout.AcceptedEntries);
    }

    [Fact]
    public async Task Files_under_assets_are_accepted_and_are_not_unknown_entries()
    {
        var archive = Build(
            File("reading/exam.json", "{}"),
            Bytes("assets/aptis-listening-t24/1.mp3", [0x49, 0x44, 0x33, 0x00]));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.True(result.IsAcceptable, Describe(result));
        Assert.Contains("assets/aptis-listening-t24/1.mp3", result.Layout.AssetEntries);
        Assert.Contains("reading/exam.json", result.Layout.AcceptedEntries);
        Assert.DoesNotContain(result.Findings, f => f.Code == ArchiveFindingCodes.LayoutUnknownEntry);
    }

    [Fact]
    public async Task A_root_manifest_paired_with_a_non_json_file_does_not_take_the_shortcut()
    {
        // Structural, not content-based (the class stays blind to content):
        // the second root file must itself end in .json, or this falls back
        // to the ordinary unknown-entry handling.
        var archive = Build(File("manifest.json", "{}"), File("notes.txt"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.False(result.IsAcceptable);
        Assert.Contains(result.Findings, f => f.Code == ArchiveFindingCodes.LayoutEmpty && f.Severity == Error);
    }

    [Fact]
    public async Task Three_root_json_files_do_not_take_the_manifest_shortcut()
    {
        // Only exactly two root files (manifest.json + one other) is
        // unambiguous. A third root file falls back to ordinary handling
        // rather than guessing which of the others is the real exam file.
        var archive = Build(File("manifest.json", "{}"), File("exam.json", "{}"), File("extra.json", "{}"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.False(result.IsAcceptable);
        Assert.Contains(result.Findings, f => f.Code == ArchiveFindingCodes.LayoutEmpty && f.Severity == Error);
    }

    [Fact]
    public async Task Every_finding_is_reported_at_once_not_just_the_first()
    {
        var archive = Build(File("../a.txt"), File("reading/CON.txt"), File("reading/x.zip"));

        var result = await inspector.InspectAsync(archive, Tight, default);

        Assert.Equal(
            [ArchiveFindingCodes.PathEscape, ArchiveFindingCodes.PathInvalid, ArchiveFindingCodes.NestedArchive, ArchiveFindingCodes.LayoutEmpty],
            result.Findings.Select(f => f.Code));
    }

    [Fact]
    public async Task No_finding_message_reveals_a_numeric_limit()
    {
        var limits = Tight with { MaxEntries = 3, MaxCompressionRatio = 7, MaxEntryUncompressedBytes = 999, MaxTotalUncompressedBytes = 1_234, MaxArchiveBytes = 55_555 };
        var archives = new[]
        {
            Bomb(1_500),
            Build(File("reading/big.txt", new string('a', 1_100))),
            Build(Enumerable.Range(0, 4).Select(i => File($"reading/{i}.txt")).ToArray()),
        };

        foreach (var archive in archives)
        {
            var result = await inspector.InspectAsync(archive, limits, default);

            Assert.False(result.IsAcceptable);
            foreach (var finding in result.Findings)
            {
                foreach (var number in new[] { "3", "7", "999", "1234", "1,234", "55555" })
                    Assert.DoesNotContain(number, finding.Message, StringComparison.Ordinal);
            }
        }
    }

    // ── Extraction ───────────────────────────────────────────────────────

    [Fact]
    public async Task Extraction_places_accepted_files_only_under_a_fresh_directory_in_the_sandbox()
    {
        var archive = Build(File("reading/p1.txt", "passage"), File("speaking/q.txt", "cue"), File("stray.txt", "no"));
        var inspection = await inspector.InspectAsync(archive, Tight, default);

        var extraction = await inspector.ExtractToSandboxAsync(archive, inspection, sandbox, Tight, default);

        Assert.True(extraction.IsSuccess, Describe(extraction));
        var directory = extraction.SandboxDirectory!;
        Assert.StartsWith(Path.GetFullPath(sandbox) + Path.DirectorySeparatorChar, directory, StringComparison.OrdinalIgnoreCase);
        Assert.Equal("passage", await System.IO.File.ReadAllTextAsync(Path.Combine(directory, "reading", "p1.txt")));
        Assert.Equal("cue", await System.IO.File.ReadAllTextAsync(Path.Combine(directory, "speaking", "q.txt")));
        Assert.False(System.IO.File.Exists(Path.Combine(directory, "stray.txt")), "an unknown entry was extracted");
        Assert.Equal(2, extraction.FilesWritten);
        Assert.Equal("passage".Length + "cue".Length, extraction.BytesWritten);

        var everything = Directory.GetFiles(sandbox, "*", SearchOption.AllDirectories);
        Assert.Equal(2, everything.Length);
        Assert.All(everything, f => Assert.StartsWith(directory, f, StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task Two_extractions_of_the_same_package_never_share_a_directory()
    {
        var archive = FullPackage();
        var inspection = await inspector.InspectAsync(archive, Tight, default);

        var first = await inspector.ExtractToSandboxAsync(archive, inspection, sandbox, Tight, default);
        var second = await inspector.ExtractToSandboxAsync(archive, inspection, sandbox, Tight, default);

        Assert.True(first.IsSuccess && second.IsSuccess);
        Assert.NotEqual(first.SandboxDirectory, second.SandboxDirectory);
    }

    [Fact]
    public async Task Extraction_refuses_an_inspection_that_was_not_acceptable()
    {
        var archive = Traversal();
        var inspection = await inspector.InspectAsync(archive, Tight, default);

        await Assert.ThrowsAsync<InvalidOperationException>(
            () => inspector.ExtractToSandboxAsync(archive, inspection, sandbox, Tight, default));

        Assert.False(Directory.Exists(sandbox) && Directory.EnumerateFileSystemEntries(sandbox).Any());
    }

    [Fact]
    public async Task A_header_that_lies_about_its_size_is_caught_by_the_streaming_quota_and_the_sandbox_is_removed()
    {
        // Declared 100 bytes, delivers 3,000: inspection passes on the
        // declared figure, extraction counts the real one.
        var archive = LyingHeader("reading/liar.bin", realSize: 3_000, declaredSize: 100);
        var inspection = await inspector.InspectAsync(archive, Tight, default);
        Assert.True(inspection.IsAcceptable, Describe(inspection));

        var extraction = await inspector.ExtractToSandboxAsync(archive, inspection, sandbox, Tight, default);

        Assert.False(extraction.IsSuccess);
        Assert.Equal(ArchiveFindingCodes.ExtractionQuotaExceeded, Assert.Single(extraction.Findings).Code);
        Assert.Null(extraction.SandboxDirectory);
        AssertSandboxEmpty();
    }

    [Fact]
    public async Task A_header_that_lies_within_the_quota_is_still_refused()
    {
        var archive = LyingHeader("reading/liar.bin", realSize: 900, declaredSize: 100);
        var inspection = await inspector.InspectAsync(archive, Tight, default);

        var extraction = await inspector.ExtractToSandboxAsync(archive, inspection, sandbox, Tight, default);

        Assert.False(extraction.IsSuccess);
        Assert.Equal(ArchiveFindingCodes.EntrySizeMismatch, Assert.Single(extraction.Findings).Code);
        AssertSandboxEmpty();
    }

    [Fact]
    public async Task Extraction_re_checks_every_entry_against_the_archive_it_is_given()
    {
        // The inspection came from a clean archive; the stream handed to
        // extraction is hostile. The inspection is never trusted over the bytes.
        var clean = Build(File("reading/ok.txt"));
        var inspection = await inspector.InspectAsync(clean, Tight, default);

        var extraction = await inspector.ExtractToSandboxAsync(Traversal(), inspection, sandbox, Tight, default);

        Assert.False(extraction.IsSuccess);
        Assert.Equal(ArchiveFindingCodes.PathEscape, Assert.Single(extraction.Findings).Code);
        AssertSandboxEmpty();
    }

    [Fact]
    public async Task Extraction_times_out_and_removes_the_sandbox()
    {
        var archive = FullPackage();
        var inspection = await inspector.InspectAsync(archive, Tight, default);
        var limits = Tight with { ExtractionTimeout = TimeSpan.FromMilliseconds(5) };

        var extraction = await inspector.ExtractToSandboxAsync(
            Slow(archive, perRead: TimeSpan.FromMilliseconds(150)), inspection, sandbox, limits, default);

        Assert.False(extraction.IsSuccess);
        Assert.Equal(ArchiveFindingCodes.ExtractionTimeout, Assert.Single(extraction.Findings).Code);
        AssertSandboxEmpty();
    }

    [Fact]
    public async Task A_cancelled_caller_token_propagates_rather_than_becoming_a_verdict()
    {
        var archive = FullPackage();
        var inspection = await inspector.InspectAsync(archive, Tight, default);
        using var cancelled = new CancellationTokenSource();
        cancelled.Cancel();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(
            () => inspector.ExtractToSandboxAsync(archive, inspection, sandbox, Tight, cancelled.Token));

        AssertSandboxEmpty();
    }

    // ── Options seam ─────────────────────────────────────────────────────

    [Fact]
    public void Options_defaults_are_sane_and_nonsense_is_reported_all_at_once()
    {
        Assert.Empty(new ImportArchiveOptions().Problems());

        var broken = new ImportArchiveOptions
        {
            MaxEntries = 0, MaxCompressionRatio = -1, ExtractionTimeoutSeconds = 0,
            MaxEntryUncompressedBytes = 10, MaxTotalUncompressedBytes = 5,
        };

        var problems = broken.Problems();

        Assert.Equal(4, problems.Count);
        Assert.All(problems, p => Assert.StartsWith("Import:Archive:", p, StringComparison.Ordinal));
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private static void AssertRefused(ArchiveInspection result, string code, string? path = null)
    {
        Assert.False(result.IsAcceptable, "expected a refusal but the archive was acceptable");
        var finding = Assert.Single(result.Findings, f => f.Code == code);
        Assert.Equal(Error, finding.Severity);
        if (path is not null) Assert.Equal(path, finding.Path);
    }

    private void AssertSandboxEmpty()
    {
        if (!Directory.Exists(sandbox)) return;
        Assert.Empty(Directory.EnumerateFileSystemEntries(sandbox));
    }

    private static string Describe(ArchiveInspection result) =>
        string.Join("; ", result.Findings.Select(f => $"{f.Severity} {f.Code} {f.Path}: {f.Message}"));

    private static string Describe(ArchiveExtraction result) =>
        string.Join("; ", result.Findings.Select(f => $"{f.Severity} {f.Code} {f.Path}: {f.Message}"));

    public void Dispose()
    {
        if (Directory.Exists(sandbox)) Directory.Delete(sandbox, recursive: true);
    }
}
