using Vni.Ielts.Application.Common;
using Vni.Ielts.Domain.Common;
using Vni.Ielts.Domain.Identity;

namespace Vni.Ielts.Application.Identity;

/// <summary>
/// What a provider tells us about the person who just signed in.
///
/// <b>Nothing here is taken from the client.</b> Every field is read out of a
/// token the API fetched from the provider's own endpoint and validated
/// itself — signature, issuer, audience, expiry and nonce. A client-supplied
/// profile is the token-substitution half of threat <c>T2</c>.
/// </summary>
/// <param name="Subject">
/// The provider's stable identifier for this person. <b>Never the email
/// address</b>, which people change; a linked account must survive that.
/// </param>
/// <param name="EmailVerified">
/// Whether the provider asserts it has verified the address. This is not the
/// same question as whether the provider *returned* an address, and the two
/// were conflated in an earlier design. Only a true here can link silently.
/// → ADR-0013
/// </param>
public sealed record ExternalIdentity(
    IdentityProvider Provider,
    string Subject,
    string? Email,
    bool EmailVerified,
    string? DisplayName);

/// <summary>
/// The per-request values the authorization URL is built from. They are
/// generated by the application and kept server-side; the client sees only the
/// finished URL. → ADR-0014
/// </summary>
public sealed record AuthorizationRequest(string State, string CodeChallenge, string Nonce);

/// <summary>
/// One identity provider, as the application sees it.
///
/// <para>
/// Implementations live in Infrastructure and are the only place a provider's
/// endpoints, client id, client secret or JWKS exist. Application knows a
/// provider by its <see cref="IdentityProvider"/> value and nothing more,
/// which is what makes adding one a new adapter rather than a change to the
/// sign-in rules (<c>AU-6</c>).
/// </para>
/// </summary>
public interface IExternalIdentityProvider
{
    IdentityProvider Provider { get; }

    /// <summary>
    /// Whether this provider's <c>email_verified</c> assertion can be trusted
    /// for silent linking.
    ///
    /// <para>
    /// <b>This is a per-provider fact, not a configuration switch, and it must
    /// never be made one.</b> Google's ID token carries the claim; Facebook's
    /// Graph response has no equivalent, so a Facebook address is an unproven
    /// claim no matter what an operator would prefer. Turning this into a
    /// setting would make reopening threat <c>T1</c> a one-line change in an
    /// environment file. → ADR-0013
    /// </para>
    /// </summary>
    bool AssertsEmailVerification { get; }


    /// <summary>
    /// Asynchronous because the authorization endpoint is read from the
    /// provider's discovery document rather than pasted into the code. That
    /// document is also where the signing keys come from, so it has to be
    /// fetchable at this point anyway — discovering it here means a
    /// misconfiguration fails at the start of the flow rather than after the
    /// user has already consented.
    /// </summary>
    Task<Uri> BuildAuthorizationUrlAsync(AuthorizationRequest request, CancellationToken ct);

    /// <summary>
    /// Exchanges the authorization code and returns the validated identity.
    ///
    /// <paramref name="nonce"/> is the value that was bound into the
    /// authorization request; the implementation must compare it against the
    /// token's own claim and fail if they differ. Passing it in rather than
    /// letting the adapter remember it keeps the adapter stateless, which
    /// matters because several sign-ins are in flight at once.
    /// </summary>
    Task<Result<ExternalIdentity>> ExchangeCodeAsync(
        string code, string codeVerifier, string nonce, CancellationToken ct);
}

/// <summary>
/// The providers this deployment actually has credentials for.
///
/// The registry exists so the API can answer "which buttons should the sign-in
/// page enable" from configuration instead of the client hard-coding three.
/// A provider with no client id is absent here rather than present and broken.
/// </summary>
public interface IExternalIdentityProviderRegistry
{
    IReadOnlyCollection<IExternalIdentityProvider> Enabled { get; }

    /// <summary>Resolves the URL segment — "google", "facebook" — case-insensitively.</summary>
    bool TryResolve(string providerKey, out IExternalIdentityProvider provider);
}

/// <summary>
/// One in-flight authorization request, held between <c>/start</c> and the
/// provider's callback.
/// </summary>
public sealed record SsoState(
    string State,
    IdentityProvider Provider,
    string CodeVerifier,
    string Nonce,
    string? ReturnTo,
    DateTimeOffset ExpiresAt);

/// <summary>
/// Where in-flight authorization requests live.
///
/// <para>
/// Server-side, not in a cookie. A cookie would work for the browser and would
/// not survive the Capacitor case, where the redirect returns through a custom
/// scheme; and the PKCE verifier must not be readable by anything on the
/// device. Storage is keyed by a hash of the state value, so a dump of the
/// collection does not yield usable states.
/// </para>
/// </summary>
public interface ISsoStateStore
{
    Task StoreAsync(SsoState state, CancellationToken ct);

    /// <summary>
    /// Single use. An unknown, expired or already-consumed state all return
    /// null — a state that can be replayed provides no CSRF protection at all.
    /// </summary>
    Task<SsoState?> ConsumeAsync(string state, CancellationToken ct);
}

/// <summary>
/// The one-time code the callback redirect carries back to the client, which
/// the client exchanges for a token pair.
///
/// <para>
/// Deliberately opaque and stored hashed rather than being a signed token.
/// A JWT here would be usable by anyone who read it out of the redirect until
/// it expired, with no way to revoke it — reintroducing on a sixty-second
/// scale the problem refresh-token rotation exists to solve. → ADR-0014
/// </para>
/// </summary>
public interface IHandoffCodeStore
{
    /// <summary>Returns the plaintext code. Only its hash is stored.</summary>
    Task<string> IssueAsync(UserId userId, CancellationToken ct);

    /// <summary>Single use. Unknown, expired and already-redeemed are one answer.</summary>
    Task<UserId?> ConsumeAsync(string code, CancellationToken ct);
}
